### ISSUE TITLE
Factions standing

### ISSUE THREAD

**Issue by duploli** [nemesis1782/XRebirthSaveGameEditor#2]
From the readme: _Factions (does not work as intended)_
I have looked in the save game, more details at the bottom.

The games seems to save in the self-closing tag _relation_ the standing value at the game beginning.
It saves the bonus/malus added to this value in a second self-closing tag _booster_ which seems to contains the last time value it was updated. Only player towards a factions (and vice-versa) have this booster tag, never a non-player faction towards another one.

The tags are written on both factions (faction A ´<relation to B is 10>´ __AND__ faction B ´<relation to A is 10>´ ). So updating a value has to be done on both factions (currently it's not done by the functions).

I'm trying to fix this in the branch _Faction_Standing_, without change to the GUI.

In the savegame file we start at the node `<factions>` then `<relations>`
## Self-closing tag _relation_
If  
```<faction id="sonraenergy"> <relations> <relation faction="familyryak" relation="-0.0032"/>``` Then
```<faction id="familyryak"> <relations> <relation faction="sonraenergy" relation="-0.0032"/>```
Moreover it seem from my observations between two savegame that the relation value of this tag do not change with time. It is probably the "base" relation value toward the relation will tends with time if nothing append (no fight, commerce...). Or it is the standing at the beginning of the game.
Should we still allow to change this tag value?

## Self-closing tag _booster_
If  
```<faction id="chow"><relations><booster faction="player" relation="0.006" time="156060.6"/>``` Then
```<faction id="player"> <relations> <booster faction="chow" relation="0.006" time="156060.6"/>```
This value seems to contains the actual relation bonus/malus between the player and another faction.
We probably should change this tag value to improve the player standing.

However, I'm not sure about the value *time*. All value seems to be lower than my `<game id="XR" (...) time="156121.0"` tag. Which possibly means that this is the last time the value was modified.

**Comment by nemesis1782** [comment]
Ah ok. So that why it didn't work well at the time.

Looks great I agree. I think we should have the user change the booster elements values not the relation elements values.

Greetz,

Davy
________________________________

**Comment by duploli** [comment]
Status at commit 1b842b6:
### What does work
The faction tab shows the booster values.
Adding button are now directed on the booster related function.
**Solved**: Changing any value will change the value on the other faction *when changing faction*.

### What does not work
 - **Done, button removed:** *Remove row* button only remove the booster on the selected faction, not on both factions. 
      - *I don't know how to change this behaviour* as we directly suppress the *BoosterData* and I don't see how to retrieve both factions names. 
      - *Possible solution*: removing the remove button, set the relation value at 0.0 should does the same
 - **Solved, faction is created if needed**: Some factions does not have a `<faction><faction id="neutral">` tag (for example neutral faction). This cause crash if trying to add a relation on them (because ```FactionData TargetedFaction = factionsData[faction];``` return a null value, the next function crash).
 - **Solved**: *Add* button does not  add the good faction name on the second faction (will be fixed asap, I just discovered it right now).
 - **Solved**: The list of faction next to the add button increases at each adding. Not yet looked why.

### Improvement to do
 - Selecting the player by default at the start.
> Changing any value will change the value on the other faction *when changing faction*
 - **Done**: Relation are updated when user stop edit mod in a cell (with ``CellEndEdit``). The update done in `comboBoxFaction_SelectedIndexChanged` function is redundant, but there is no speed issue, si I will probably keep it.

### What is not tested
 - **Tested, it works:** Adding a booster value between 2 non-player faction. I did not see it in any of my savegame. *I will try to make everybody angry against everybody, just to know if it works*

**Comment by nemesis1782** [comment]
Hey,


great work [😊]


Remove row button only remove the booster on the selected faction, not on both factions.

  *   I don't know how to change this behaviour as we directly suppress the BoosterData and I don't see how to retrieve both factions names.
  *   Possible solution: removing the remove button, set the relation value at 0.0 should does the same

The solution provided as possible solution should do the trick and is suffiecient.


Greetz,


Davy

________________________________
