### ISSUE TITLE
Unable to locate t node

### ISSUE THREAD

**Issue by duploli** [nemesis1782/XRebirthSaveGameEditor#4]
Some warnings at startup:
```
----------------------------------------
Category: Warning - Timestamp: 25/11/2017 15:18:11 
Message: Unable to locate t node
----------------------------------------
Category: Warning - Timestamp: 25/11/2017 15:18:11 
Message: Unable to parse {20108,2501}
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   Ã  X_Rebirth_Save_Game_Editor.CatDatExtractor.GetTranslationCategory(String language) in C:\...\XRebirthSaveGameEditor\Source\X_Rebirth_Save_Game_Editor\CatDatExtractor.cs:ligne 397
StackTrace:    Ã  X_Rebirth_Save_Game_Editor.CatDatExtractor.GetTranslationCategory(String language) dans C:\...\XRebirthSaveGameEditor\Source\X_Rebirth_Save_Game_Editor\CatDatExtractor.cs:ligne 397
```

Probably due to [this test](https://github.com/nemesis1782/XRebirthSaveGameEditor/blob/master/Source/X_Rebirth_Save_Game_Editor/CatDatExtractor.cs#L380) because nothing force the first pair value (`iden[0]`) to be equal for the entire list. This leads to the warning as soon as the page ID change.

It it solved in 9c1e36ce5, may be a little slower but more robust.

**Comment by nemesis1782** [comment]
This is merged into the base right? Is there a good place to see the branch overview in github?

**Comment by nemesis1782** [comment]
Alright found the branch overview and merged the pull requests. This issue is solved right?

**Comment by duploli** [comment]
It's good for me ;-)
